name: weappear_backend
version: 1.0.0
description: WeAppe.ar backend
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  base32: ^2.1.3
  dart_jsonwebtoken: ^2.4.1
  dbcrypt: ^2.0.0
  dotenv: ^3.0.0
  equatable: ^2.0.5
  http: ^0.13.4
  http_parser: ^4.0.0
  json_annotation: ^4.7.0
  mailer: ^5.1.0
  mime: ^1.0.3
  mongo_dart: ^0.7.4
  mongo_dart_query: ^1.0.2
  ootp: ^0.1.1
  path: ^1.8.0
  queue: ^3.1.0+1
  retry: ^3.1.0
  shelf: ^1.4.0
  shelf_hotreload: ^1.3.0
  shelf_router: ^1.1.3
  shelf_swagger_ui: ^1.0.0+2
  timezone: ^0.9.0
  
dev_dependencies: 
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  pubspec_dependency_sorter: ^0.0.1
  recharge: ^0.1.0
  very_good_analysis: ^3.1.0
