name: weappear_backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  dart_jsonwebtoken: ^2.4.1
  dbcrypt: ^2.0.0
  dotenv: ^3.0.0
  http: ^0.13.4
  http_parser: ^4.0.0
  mailer: ^5.1.0
  mongo_dart: ^0.7.4
  mongo_dart_query: ^1.0.2
  path: ^1.8.0
  shelf: ^1.4.0
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.3
  shelf_swagger_ui: ^1.0.0+2
  queue: ^3.1.0+1
  retry: ^3.1.0
  mime: ^1.0.3
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  recharge: ^0.1.0
  very_good_analysis: ^3.1.0